name: Generate Collections

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        collection:
          [
            "dbmultiverse",
            "strip",
            "namekseijin",
            "dbm-colors",
            "chibi-son-bra",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Collection ${{ matrix.collection }}
        run: python dbmultiverse.py ${{ matrix.collection }}

      - name: Upload Collection ${{ matrix.collection }} to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: collection-${{ matrix.collection }}
          path: ./DragonBallMultiverse-${{ matrix.collection }}.pdf

      - name: Create Release and Upload Asset
        uses: gh-actions/create-release@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag_name: DragonBallMultiverse-${{ matrix.collection }}-${{ github.sha }}
          release_name: DragonBallMultiverse-${{ matrix.collection }} Release of ${{ github.sha }}
          body: New release for DragonBallMultiverse-${{ matrix.collection }}
          draft: false
          prerelease: false
          asset_path: ./DragonBallMultiverse-${{ matrix.collection }}.pdf
          asset_name: DragonBallMultiverse-${{ matrix.collection }}.pdf
          asset_content_type: application/pdf
