name: Generate Collections

on:
  push:
    branches:
      - main # or whichever branch you use

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        collection:
          [
            "dbmultiverse",
            "strip",
            "namekseijin",
            "dbm-colors",
            "chibi-son-bra",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Collection ${{ matrix.collection }}
        run: python your_script_name.py --collection ${{ matrix.collection }}

      - name: Upload Collection ${{ matrix.collection }} to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: collection-${{ matrix.collection }}
          path: path_to_generated_pdfs/${{ matrix.collection }}/
