name: Generate Collections

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Collection
        run: python dbmultiverse.py all

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Release DragonBallMultiverse PDFs
        uses: ncipollo/release-action@v1
        with:
          # token: ${{ secrets.GH_TOKEN }}
          allowUpdates: true
          tag: DragonBallMultiverse-PDF-latest
          commit: ${{ github.sha }}
          artifacts: ./DragonBallMultiverse-dbmultiverse.pdf,./DragonBallMultiverse-dbm-colors.pdf,./DragonBallMultiverse-chibi-son-bra.pdf,./DragonBallMultiverse-namekseijin.pdf,./DragonBallMultiverse-strip.pdf
